language: ruby
sudo: false

cache:
- bundler
- apt

script: 
- bundle exec gem build gollum-site.gemspec
- bundle exec gem install gollum-site-0.1.12.KMS.gem
- bundle show gollum-site
- bundle exec gollum-site
- export $BUNDLE_GEMFILE=$PWD/gollum-site.gemfile
- ls
- cd ../
- git clone https://github.com/Kevin-M-Smith/wiki.wiki.git
- cd wiki.wiki
- bundle exec gollum-site generate
