language: ruby
sudo: false

cache:
- bundler
- apt

script: 
- bundle exec gem build gollum-site.gemspec
- bundle exec gem install gollum-site-0.1.12.KMS.gem
- cd ../
- git clone https://github.com/Kevin-M-Smith/wiki.wiki.git
- cd wiki.wiki
- gollum-site generate
