language: ruby
sudo: false

cache:
- bundler
- apt

script: bundle exec gem install gollum-site

after_success:
- sudo gem install gollum-site
- git clone https://github.com/Kevin-M-Smith/wiki.wiki.git
- cd wiki.wiki
- gollum-site generate
