language: ruby
sudo: false

branches:
  only: master

cache:
- bundler
- apt

script: 
- bundle exec gem build gollum-site.gemspec
- bundle exec gem install gollum-site-0.1.12.KMS.gem
- bundle show gollum-site
- bundle exec gollum-site
- export BUNDLE_GEMFILE=$PWD/Gemfile
- echo $BUNDLE_GEMFILE
- pwd
- ls
- git clone --single-branch --branch gh-pages https://github.com/Kevin-M-Smith/wiki.git wiki-pages
- cd ../
- git clone https://github.com/Kevin-M-Smith/wiki.wiki.git
- cd wiki.wiki
- export WIKI_VERISON=`git rev-parse HEAD`
- bundle exec gollum-site generate ../wiki-pages/
- cd ../wiki-pages
- git status
